update glu archive URL
flathub/shared-modules pull request #239
Opened 2023-03-11 21:04 UTC by christianrauch

The old URL gives me:
```
Downloading sources
Downloading https://mesa.freedesktop.org/archive/glu/glu-9.0.2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    268      0 --:--:-- --:--:-- --:--:--   268
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Failed to download sources: module glu: server certificate verification failed. CAfile: none CRLfile: none
```
when using `flatpak-builder` locally, and:
```
$ curl https://mesa.freedesktop.org/archive/glu/glu-9.0.3.tar.xz 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

2023-03-11 23:09 UTC, ranisalt commented
A better option would be `https://archive.mesa3d.org/glu/glu-9.0.2.tar.xz`, the URL that the current URL redirects to, which would not require changing the checksum & archive type.

2023-03-24 17:05 UTC, hfiguiere requested changes
As mentionned there is a better alternative.

2023-03-24 21:44 UTC, christianrauch commented
Is updating the checksum a problem?

The source is directly from the upstream repo at https://gitlab.freedesktop.org/mesa/glu. This is where I would expect to find the original source.

2023-03-24 21:51 UTC, ranisalt commented
The source from mesa3d.org has signed downloads: https://archive.mesa3d.org/glu/ so the checksum can be verified and trusted. The download from freedesktop gitlab does not display a checksum for checking, you have to download it and calculate, which is too late.

2023-03-25 13:36 UTC, christianrauch commented
> The source from mesa3d.org has signatures: https://archive.mesa3d.org/glu/ so the checksum can be verified and trusted. The download from freedesktop gitlab does not display a checksum for checking, you have to download it and calculate, which is too late.

Ah, thanks. That makes sense. So I updated to URL only now.

But, how do you extract the checksum from the signature (`glu-9.0.2.tar.xz.sig`)? I guess you can use the signature to verify the file, but I cannot find how to just get the sha256.

2023-03-25 13:55 UTC, ranisalt commented
> But, how do you extract the checksum from the signature (`glu-9.0.2.tar.xz.sig`)? I guess you can use the signature to verify the file, but I cannot find how to just get the sha256.

As far as I'm concerned, you can't, but if the signature verifies correct, you can be sure that the file is correct and has not been manipulated. You can then calculate the checksum with `sha256sum` (or other variants) or using `gpg` with `--print-md <algo>` or `--print-mds` which will calculate several different hashes.

2023-03-25 13:55 UTC, ranisalt approved these changes

2023-03-25 14:06 UTC, christianrauch commented
> > But, how do you extract the checksum from the signature (`glu-9.0.2.tar.xz.sig`)? I guess you can use the signature to verify the file, but I cannot find how to just get the sha256.
> 
> As far as I'm concerned, you can't, but if the signature verifies correct, you can be sure that the file is correct and has not been manipulated. You can then calculate the checksum with `sha256sum` (or other variants) or using `gpg` with `--print-md <algo>` or `--print-mds` which will calculate several different hashes.

But then the argument about not having to change the checksum does not make sense. If you cannot verify the download via the signature file in flatpak builder and have to download and compute the checksum manually anyway, then it does not matter which file you download. I.e. how do you know that the person adding the sha256 did verify the archive via the signature? If the build tool does not verify the signature, then it does not matter if you use the archive with or without a signature.

2023-05-05 01:51 UTC, merged